print("                   ***                                ")
print("                   ** **                              ")
print("                 **   **                              ")
print("                 **   **         ****                 ")
print("                 **   **       **   ****              ")
print("                 **  **       *   **   **             ")
print("                   **  *      *  **  ***  **          ")
print("                   **  *    *  **     **  *           ")
print("                     ** **  ** **        **           ")
print("                     **   **  **                      ")
print("                   *           *                      ")
print("                   *             *                    ")
print("                 *    0     0    *                    ")
print("                 *   /   @   \   *                    ")
print("                 *   \__/ \__/   *                    ")
print("                   *     W     *                      ")
print("                     **     **                        ")
print("                       *****                          ")

# Credit https://www.asciiart.eu/animals/rabbits